### PR TITLE
Local Package Tile View Implementation

### PR DESCRIPTION
**Pull request by punker76**
After implementing the tile view for the remote source it's more consequent to do this for the local package view too.

Changes
- Same tile view for local view
- Fix DataGrid sorting for Title and Authors

choco_local_tileview

2017-10-30_22h52_35

2017-10-31_00h03_29

Relates to #517

### CODE REVIEW

**Comment by RichiCoder1** [comment]
What's the bookmark symbol represent?

**Comment by punker76** [comment]
@RichiCoder1 It's the `IsSideBySide` status.

**Comment by punker76** [comment]
Sorting for Title and Authors fixed

choco_local_sorting

**Comment by punker76** [comment]
@gep13 @RichiCoder1 I think I'm done for now. So there are only 2 things. Saving (and default) for the tile configuration. And second is, if we should also show a sorting ComboBox if the tile view is selected (where the user can sort by title, author, version, last version)?

**Comment by RichiCoder1** [comment]
@punker76 Awesome work again :)

>  Saving (and default) for the tile configuration. 

At least for now I'd add a switch in settings like console output toggle.

> And second is, if we should also show a sorting ComboBox if the tile view is selected (where the user can sort by title, author, version, last version)?

Yup! I know that's going to be the one of the first requests we get after rolling this out

**Comment by punker76** [comment]
@RichiCoder1 

> Yup! I know that's going to be the one of the first requests we get after rolling this out

ok, will do this in next days

**Comment by gep13** [comment]
@punker76 epic work!

I have merged this into develop now, I think the outstanding items should be raised as separate issues, as the main part of #517 has been completed.

**Pull request merged**
