### PR TITLE
Add check for background service

### LINKED ISSUE #371: Add check for useBackgroundService
ChocolateyGUI needs to look in the config file and see if features/useBackgroundService is there and if it is set to true.

Then allow running install/upgrade without trying to seek admin rights.

### PR DESCRIPTION
**Pull request by RichiCoder1**
Also fix a few typos and back resources.

Closes #371

### CODE REVIEW

**Comment by RichiCoder1** [comment]
Had a change to poke at this @ferventcoder?

**Comment by ferventcoder** [comment]
I did, but there is an issue I am going to dive deeper into this week to see whether it stems from this or from the API.

**Comment by RichiCoder1** [comment]
*bump*

**Comment by ferventcoder** [comment]
Gary and I looked deeper into this - what is happening is the licensed.dll seems to run into an error that is super hard to determine - may need to find a way to attach a debugger. What I think it is - because the licensed edition takes a dependency on choco.exe, it's having issues when it is the DLL instead.

**Comment by RichiCoder1** [comment]
Odd. Let me know how I can assist. I believe the chocolatey.lib includes symbols right? Even if not, you should be able to switch Gui's reference to a locally build version, turn off exact source match in debug settings, and then just attached a debugger with `chocolatey` to Gui. The ilmerge might futz with things though, and I'm not sure if and how to make Gui work directly with the source dlls....

**Comment by RichiCoder1** [comment]
*bump*

**Comment by ferventcoder** [comment]
There have been some fixes into chocolatey.lib and the extension that may fix this. Getting ready to try this again.

**Comment by RichiCoder1** [comment]
Excellent! I'd merge mainline develop into this as it just updated all the the packages (including lib)

**Comment by ferventcoder** [comment]
Can I push to this PR?

**Comment by RichiCoder1** [comment]
Absolutely

**Comment by ferventcoder** [comment]
Should I wait until we get the other through? I prefer to reduce merge conflicts and so much has changed.

**Comment by RichiCoder1** [comment]
#438 is merged and cleaned up. You should be good to go now.

**Comment by RichiCoder1** [comment]
Brought this branch back up to Develop. Builds and runs just fine, though I'm not sure how much of the BP functionality is still preserved.

**Comment by ferventcoder** [comment]
BP?

**Comment by RichiCoder1** [comment]
Background service stuff. BS doesn't have the same ring haha.

**Comment by ferventcoder** [comment]
Ah true!

**Comment by ferventcoder** [comment]
Superseded by #451

**Pull request closed without merging**
