### PR TITLE
More UI improvements related to #509

### LINKED ISSUE #512: Autofocus search boxes on SourceViews
If the application is in focus, it should focus the appropriate search box for a source view upon navigation.

### PR DESCRIPTION
**Pull request by punker76**
- Use MahApps CheckBox style (also for DataGridCheckBoxColumn)
- Use MahApps TextBox style
- German LocalSourceView_SearchBoxText without space at the end
- Same header UI for LocalSourceView and RemoteSourceView
  - ToolTipService.ShowOnDisabled="True" for buttons
  - PackIconFontAwesome Refresh for refresh package list
  - PackIconFontAwesome Refresh and Asteriks for refresh all
  - PackIconFontAwesome FloppyOutline for export
- Use ListBox at SourcesView and ItemTemplate for the data
- Autofocus search boxes on SourceViews
- Use flat button style for icon buttons on header (IconFlatButtonStyle derived from MetroFlatButton)

Closes #512 

**Before**

2017-10-26_23h38_08

2017-10-26_23h38_20

**After**

2017-10-26_22h35_32

2017-10-26_22h35_39

2017-10-26_23h38_52

### CODE REVIEW

**Comment by RichiCoder1** [comment]
Looks great from a quick overview, though I'm not super happy with the button styles. They looks really out of place and dated. That may be something we refine after merge though.

I'll pull this down later and play with source switching and approve if good after that.

**Comment by punker76** [comment]
@RichiCoder1 What do you think about a flat button design for the icon buttons

2017-10-27_09h02_55

2017-10-27_09h03_06

**Comment by gep13** [comment]
@punker76 would you be in a position to rebase this PR on latest develop?  I have fixed the build error that I introduced last night.

**Comment by punker76** [comment]
@gep13 yeah ✔️

**Comment by gep13** [comment]
@punker76 perfect, so that is the build working again.  Once @RichiCoder1 is happy, we can get this merged into develop as well (we can remove the extra merge commit before the final merge, just to keep the git history a little cleaner 😄)

**Comment by punker76** [comment]
@gep13 I can make a new PR with my changes including the last suggestion for the icon buttons

**Comment by gep13** [comment]
@punker76 no need to create a new PR, we can `git rebase` away those merge remote-tracking commits 😄

**Comment by punker76** [comment]
@gep13 @RichiCoder1 so my last question is, should I add the icon button change which I posted above with the screenshots?

**Comment by gep13** [comment]
@punker76 let me know when you are in a position to add them, and after that i can rebase this PR and get it merged.

**Comment by punker76** [comment]
@gep13 done
@RichiCoder1 I changed the background brush for the flat icon style to the brush which are used for the buttons at the bottom, looks better...

2017-10-27_20h47_34

2017-10-27_20h47_48

**Comment by gep13** [comment]
@punker76 I have rebased and force pushed your PR branch.  I will wait for the AppVeyor build to complete, and then I will merge.

In the mean time, since I have force pushed, if you want to update our local branch, you will need to do `git reset --hard origin/feature/LocalSourceView_UI_Improvements_509` as your local copy will now be out of sync with what I have done.

However, that branch can go away once the merge is complete, just wanted to let you know in case you wanted to do something.

I have removed the two merge commits that were there, as well as the two commits around changing `Suche: ` to `Suche:` as those commits were not required.

**Comment by gep13** [comment]
@punker76 your changes have been merged, thanks for your contribution 👍

**Comment by RichiCoder1** [comment]
I need to send github notifications from gui to my priority inbox haha. Looks much better @punker76!

**Comment by gep13** [comment]
@RichiCoder1 are you not using Octobox yet?  It has changed the way that I handle notifications from GitHub.

**Comment by RichiCoder1** [comment]
@gep13 Hadn't heard of it. WIll check it out.

**Comment by gep13** [comment]
https://github.com/octobox/octobox

I have a version of it running on my local NAS.  It is VERY good!

**Pull request merged**
