### PR TITLE
Re-Theme and Fixes

### PR DESCRIPTION
**Pull request by RichiCoder1**
Applies a new chocolatey-inspired theme, as well as consoidated a number of styles brushes and fixing a few misc errors.

Preview

Installing Preview

cc: @ferventcoder @gep13

### CODE REVIEW

**Comment by gep13** [comment]
@RichiCoder1 looks good to me! :+1: 

Are you planning on creating a few different themes?

**Comment by RichiCoder1** [comment]
I may eventually make a dark theme, but the plan was just to align with chocolatey.org for now

**Comment by gep13** [comment]
>@RichiCoder1 said...
I may eventually make a dark theme

Noice!  Makes sense to stick with one for the first pass, but nice to know that there is an option to change it up if/when required.

**Comment by ferventcoder** [comment]
👍

**Pull request merged**
