### PR TITLE
(GH-769) Prevent automatic outdated package check

### LINKED ISSUE #769: Add option to disable check for outdated packages
It would be nice to be able to disable the check for outdated packages on local and remote views.

Changes required: 

- [x] Setting, default disabled. We should check by default
- [x] CLI parameter
- [x] Package parameter
- [x] update button on local and remote view, this should force a check for outdated packages

### PR DESCRIPTION
**Pull request by mkevenaar**
Fixes #769

### CODE REVIEW

**Comment by mkevenaar** [comment]
Ready for review @gep13 @punker76 @AdmiringWorm @mwallner

**Comment by punker76** [comment]
After my changes...

chocogui_loading

**Comment by mkevenaar** [comment]
I have made a small change to the translation to match the feature better. I also prevented the "Show Only Packages with Updates" to be enabled when we haven't checked for outdated packages.

**Comment by gep13** [comment]
@mkevenaar your changes have been merged, thanks for your contribution 👍

**Comment by gep13** [comment]
@punker76 thanks also for your help on this!

**Pull request merged**
