### PR TITLE
Show message at remote source view when no packages were found by search input

### LINKED ISSUE #742: Explain why there are no packages in remote views
As a follow up to this [issue](https://github.com/chocolatey/ChocolateyGUI/issues/706) it would be good to provide some text when 

- [x] first going to a remote source, to explain why there are no packages displayed
- [x] when searching a remote source and no packages are found
- [x] when searching a local source and no packages are found

### PR DESCRIPTION
**Pull request by punker76**
Add a ListView template to show a message when no matching packages were found.

2020-04-04_12h03_56

2020-04-04_12h04_34

Closes #742

### CODE REVIEW

**Comment by gep13** [comment]
@punker76 thanks for doing this!  I have added another commit to add the strings to the resx file, and I will merge once the CI completes.

**Comment by gep13** [comment]
@punker76 I have just noticed a slight issue, where I can end up in this state...

image

Can you suggest what would need to change to prevent this?  Seems like both the "Empty Results" Template is being shown, and the message for the Prevent Preload.

**Comment by punker76** [comment]
@gep13 It should be work now with or without the preload feature...

choco_search_result

**Comment by gep13** [comment]
@punker76 thanks again for doing this!

**Pull request merged**
