### PR TITLE
(#786) Add confirmation for destructive operations

### LINKED ISSUE #786: Ask to confirm Uninstall/Reinstall from Right-Click Menu
When you open the right-click menu for any installed application, you should get a confirmation prompt if you click on Uninstall or Reinstall. If they are clicked accidentally when the user actually wanted to click on Pin or Details, the user might lose important data.

### PR DESCRIPTION
**Pull request by gep13**
A confirmation dialog is being added to the reinstall and uninstall
operations since these can be harmful operations to the system.

Fixes #786

### CODE REVIEW

**Comment by gep13** [comment]
@punker76 can you offer any help here?

When I try to run the application, I get the following error displayed:

image

I have tried to add the participation element, in the same way that I did here:

https://github.com/chocolatey/ChocolateyGUI/commit/59ddbf71db1ecaaebca24ccba3557396f02085cc

But no matter where I put it, it results in the same thing each time. 

Thanks

**Comment by punker76** [comment]
@gep13 I implemented as new method ShowConfirmationMessageAsync on IProgressService  and use this new method to show a confirmation dialog e.g. when the user choose Reinstall or Uninstall. Using the DialogCoordinator is not possible for this, because the PackageViewModel can not be registered to the same view as for the local or remote source view.

**Comment by gep13** [comment]
@punker76 thank you very much for fixing this up!

**Comment by opusforlife2** [comment]
Thank you! This is a major lifesaver!

**Pull request merged**
