### PR TITLE
(logo) Adding animated Choco Logo

### PR DESCRIPTION
**Pull request by gep13**
@RichiCoder1 would you have a minute to take a look at this?

### CODE REVIEW

**Comment by gep13** [comment]
When I run it initially, I get this:

image

However, when I maximize the window, it balloons to this:

image

And if I make the window smaller, it seems to go off the screen.

I am not exactly clear on what is causing the size/position to change.  Can you offer any advice here?

**Comment by gep13** [comment]
@punker76 while I have your attention...

Don't suppose you would have any input for this one would you?

Thanks in advance!

**Comment by punker76** [comment]
@gep13 Would that be okay? Or should it be more left?

choco_logo

**Comment by punker76** [comment]
@gep13 ...

choco_logo2

**Comment by punker76** [comment]
@gep13 another one...

choco_logo3

I prefer 2nd and this one.

**Comment by gep13** [comment]
Ideally, the upper left corner of the icon would always be off screen, i.e. as though the chocolate bar is off screen.  See the icon at the top left here:

https://chocolatey.org/

See how you never see the top edge of the bar?

**Comment by gep13** [comment]
So, if you could take the third one above, and bump it vertically about 15/20 pixels, I think it would be perfect 😄

**Comment by gep13** [comment]
@punker76 does the changes that you have made work if you resize the main application?  i.e. the image doesn't expand, or change position?

**Comment by punker76** [comment]
@gep13 it keeps on resizing and moving :-D

finally

choco_logo4

PR is on the way

**Comment by gep13** [comment]
@punker76 Sweet!  Thank you so much for your help with this!

**Comment by gep13** [comment]
@punker76 very curious to see how you have went about doing it 😄

**Comment by gep13** [comment]
Closing this, in favour of this one: https://github.com/chocolatey/ChocolateyGUI/pull/476

**Comment by gep13** [comment]
Nope, that isn't going to work :-)

That PR is based on top of this one :-)

**Comment by RichiCoder1** [comment]
W/ @punker76's PR, lgtm.

**Pull request merged**
