### PR TITLE
GH373: Added Wyam Documentation Generation

### PR DESCRIPTION
**Pull request by gep13**
@RichiCoder1 let me know what you think of this.

image

At the minute, it is just the very basic scaffolding for the documentation portion of the site.  However, it does include the ability to pull in top level pages, as well as the main documentation section, and also a blog for the application.

The way I have set up the cake build is that it will check to see if there are any documentation changes in the current commit, and if there are, it will run Wyam, and then push to the gh-pages branch the result of the build.  All documentation changes can be made within the `docs/input` folder.

/cc @daveaglick

### CODE REVIEW

**Comment by RichiCoder1** [comment]
Nice! I'll poke at it further in a little, but basically exactly what I had in mind :)

**Comment by gep13** [comment]
Sweet!

**Comment by daveaglick** [comment]
:tada:

**Comment by gep13** [comment]
Relates to #373

**Comment by punker76** [comment]
👍

**Pull request merged**
