### PR TITLE
Added missing translated strings for Norwegian Bokmål

### PR DESCRIPTION
**Pull request by AdmiringWorm**
Added a few missing translations, as well as the ones mentioned in issue #486 

*Sorry about the incorrect whitespace, it was added by the [resxtranslator](https://github.com/HakanL/resxtranslator) tool (this will probably be added by transifex as well when translations are moved there)*

### CODE REVIEW

**Comment by AdmiringWorm** [comment]
this one should also be merged after the PR #487 (in which case I need to rebase first)

**Comment by gep13** [comment]
@AdmiringWorm if/when you have a minute, can you rebase this? Thanks!

**Comment by AdmiringWorm** [comment]
@gep13 done

**Comment by gep13** [comment]
@AdmiringWorm your changes have been merged, thanks for your contribution 👍

**Pull request merged**
