### PR TITLE
Major Overhaul

### PR DESCRIPTION
**Pull request by RichiCoder1**
Finally happy enough with this branch to get ready to merge it in.

The changes in this branch are almost too numerous to count, but the major highlights are:
* Now using Chocolatey.Lib for as the basis for all package interactions. This involved ripping out or moving a lot of the underlying code.
* Now using Caliburn.Micro to power the "framework" of the app.
* Using Serilog for logging.
* Improved perf and UI behaviors in a few places.

Still a lot of I'd like to do, but this is going to form the basis of that work.

/cc @gep13 @ferventcoder

### CODE REVIEW

**Comment by RichiCoder1** [comment]
Getting this to go green was an adventure....

**Comment by gep13** [comment]
@RichiCoder1 epic work on this! :+1:

**Comment by RichiCoder1** [comment]
Realized I left out that I updated the theme-ing too. Will post gifs and screenshots and stuff soon. Gonna let this bake till the weekend, make sure there's no bugs, and then merge into develop. Then todos are:
- [ ] Restoring Sources / About
- [ ] Improving Error experience
- [ ] Adding Pin Functionality
- [ ] Improving loading screen UX

Then we should be good for a much overdo release candidate.

**Comment by ferventcoder** [comment]
SWEET!

**Comment by RichiCoder1** [comment]
Aaaand here we go!

**Pull request merged**
