### PR TITLE
(GH-275) Added persistence of window size and position

### LINKED ISSUE #275: Chocolatey GUI doesn't save user's preferred window position, size and state
I'm on Windows 7. ChocolateyGUI does not remember my preferred window position, size or maximized state. The first time I ran ChocolateyGUI, I moved and resized the window to workaround bug #276. However, ChocolateyGUI didn't restore its position and size on second run, and it always reverts to the default behavior on running again.

### PR DESCRIPTION
**Pull request by gep13**
Fixes #275

### CODE REVIEW

**Comment by gep13** [comment]
@ferventcoder @RichiCoder1 @mwallner I would appreciate if you could take a look at this.

**NOTE:** This won't work if debugging out of Visual Studio, as the design time height and width take over.  However, if you build the project and run the generated exe directly, you should be able to see it in action.

**Comment by punker76** [comment]
@gep13 there is also a property at `MetroWindow` which saves the position, size and state: `SaveWindowPosition="True"`

**Comment by gep13** [comment]
@punker76 oh, interesting...

Well, that might make it even easier then 😄

**Comment by gep13** [comment]
@punker76 wait...

That property is already set?!?

**Comment by gep13** [comment]
@punker76 I have just tried running the develop branch of ChocolateyGUI, and with that setting in play, closing and opening the application, is remembering the size/position.  Is there anything else that needs to be done for this to light up?

**Comment by punker76** [comment]
@gep13 Found it...

The ShellView doesn't call other Closing events, but it should do that.

```
        protected override void OnClosing(CancelEventArgs e)
        {
            if (!_closeInitiated)
            {
                e.Cancel = true;
                _closeInitiated = true;
                var bootstrapper = (Bootstrapper)Application.Current.FindResource("Bootstrapper");
#pragma warning disable 4014

                // ReSharper disable once PossibleNullReferenceException
                bootstrapper.OnExitAsync().ContinueWith(t => Execute.OnUIThread(Close));
#pragma warning restore 4014
            }
            // fire other Closing events too
            base.OnClosing(e);
        }
```

Add this line `base.OnClosing(e);` and the MetroWindow saves and loads size, position and state.

**Comment by RichiCoder1** [comment]
Oops

**Comment by gep13** [comment]
@RichiCoder1 yip, that was my thinking too.

**Comment by gep13** [comment]
@punker76 thanks for hunting down this issue.  I have just tested it out, and it works as expected :-)

**Pull request merged**
