### PR TITLE
Hotfix/0.13.2

### PR DESCRIPTION
**Pull request by gep13**

### CODE REVIEW

**Comment by gep13** [comment]
@RichiCoder1 what are your thoughts on the following:

image

**Comment by gep13** [comment]
@ScottIsAFool also, what are your thoughts on the above?

**Comment by ScottIsAFool** [comment]
Why not provide a "would you like to update chocolatey now?" option to that? Why make the user go through another step (a step not actually detailed in that message).

**Comment by gep13** [comment]
>@ScottIsAFool said...
Why not provide a "would you like to update chocolatey now?" option to that? Why make the user go through another step (a step not actually detailed in that message).

I had a feeling you were going to say that :smile_cat:

**Comment by ScottIsAFool** [comment]
Then you should have pre-empted me :P

**Comment by gep13** [comment]
Yeah, well, I was being lazy :smile_cat:

**Comment by RichiCoder1** [comment]
Looks good to me :+1:

**Comment by gep13** [comment]
Re-implemented directly in develop branch, since this PR is outdated.

**Pull request closed without merging**
