### PR TITLE
(GH-814) Use Visual Studio 2019

### PR DESCRIPTION
**Pull request by aminya**
This simplifies the build process by deprecating the old Visual Studio versions and using VS 2019.

### Benefits
- Using the latest VS means that the build errors are tested and diagnosed for the latest VS version.
- It is already 2021, and Microsoft may release Visual Studio 2021 soon, and yet Choco uses VS 2015! This PR fixes this issue.
- New Visual Studio usually means better runtime performance.

### CODE REVIEW

**Comment by aminya** [comment]
This is the error I get locally:

```ps1

========================================
Build
========================================
Executing task: Build
Executing: "C:/Users/aminy/Documents/GitHub/C#/ChocolateyGUI/tools/Cake/Cake.exe" "C:/Users/aminy/Documents/GitHub/C#/ChocolateyGUI/4b9d2b58-2314-4696-b7e5-0023e04aa216.cake" -nuget_useinprocessclient="true" -settings_skipverification="true"
Deleting file C:/Users/aminy/Documents/GitHub/C#/ChocolateyGUI/4b9d2b58-2314-4696-b7e5-0023e04aa216.cake
Building Source/ChocolateyGui.sln
Executing: "C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/MSBuild/Current/Bin/amd64/MSBuild.exe" /m /v:normal /p:Configuration="Release" /p:Platform="Any CPU" /p:TreatWarningsAsErrors=True /target:Build /logger:XmlFileLogger,"C:/Users/aminy/Documents/GitHub/C#/ChocolateyGUI/tools/MSBuild.Extension.Pack.1.9.1/tools/net40/MSBuild.ExtensionPack.Loggers.dll";logfile="BuildArtifacts/MsBuild.log";invalidCharReplacement=_;verbosity=Detailed;encoding=UTF-8 "C:/Users/aminy/Documents/GitHub/C#/ChocolateyGUI/Source/ChocolateyGui.sln"
Microsoft (R) Build Engine version 16.7.0+b89cb5fde for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 2021-02-05 6:16:08 PM.
     1>Project "C:\Users\aminy\Documents\GitHub\C#\ChocolateyGUI\Source\ChocolateyGui.sln" on node 1 (Build target(s)).
     1>MSBUILD : warning MSB4010: The "*.tasks" files could not be successfully loaded from their expected location "C:
       \Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\amd64". Default tasks will not
       be available.  [C:\Users\aminy\Documents\GitHub\C#\ChocolateyGUI\Source\ChocolateyGui.sln]
     1>C:\Users\aminy\Documents\GitHub\C#\ChocolateyGUI\Source\ChocolateyGui.sln.metaproj : error MSB4036: The "Message
       " task was not found. Check the following: 1.) The name of the task in the project file is the same as the name
       of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface.
       3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the
       "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\amd64" directory. [C:\Users\
       aminy\Documents\GitHub\C#\ChocolateyGUI\Source\ChocolateyGui.sln]
     1>Done Building Project "C:\Users\aminy\Documents\GitHub\C#\ChocolateyGUI\Source\ChocolateyGui.sln" (Build target(
       s)) -- FAILED.

Build FAILED.

       "C:\Users\aminy\Documents\GitHub\C#\ChocolateyGUI\Source\ChocolateyGui.sln" (Build target) (1) ->
       (ValidateSolutionConfiguration target) ->
         MSBUILD : warning MSB4010: The "*.tasks" files could not be successfully loaded from their expected location "
       C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\amd64". Default tasks will no
       t be available.  [C:\Users\aminy\Documents\GitHub\C#\ChocolateyGUI\Source\ChocolateyGui.sln]


       "C:\Users\aminy\Documents\GitHub\C#\ChocolateyGUI\Source\ChocolateyGui.sln" (Build target) (1) ->
       (ValidateSolutionConfiguration target) ->
         C:\Users\aminy\Documents\GitHub\C#\ChocolateyGUI\Source\ChocolateyGui.sln.metaproj : error MSB4036: The "Messa
       ge" task was not found. Check the following: 1.) The name of the task in the project file is the same as the nam
       e of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface
       . 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in th
       e "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\amd64" directory. [C:\User
       s\aminy\Documents\GitHub\C#\ChocolateyGUI\Source\ChocolateyGui.sln]

    1 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.12
An error occurred when executing task 'Build'.

----------------------------------------
Teardown
----------------------------------------
Executing custom teardown action...
Starting Teardown...
Finished running tasks.
Error: System.AggregateException: One or more errors occurred. ---> Cake.Core.CakeException: MSBuild: Process returned an error (exit code 1).
   at Cake.Core.Tooling.Tool`1.ProcessExitCode(Int32 exitCode)
   at Cake.Core.Tooling.Tool`1.Run(TSettings settings, ProcessArgumentBuilder arguments, ProcessSettings processSettings, Action`1 postAction)
   at Cake.Common.Tools.MSBuild.MSBuildAliases.MSBuild(ICakeContext context, FilePath solution, MSBuildSettings settings)
   at Submission#0.MSBuild(FilePath solution, MSBuildSettings settings)
   at Submission#0.<>c__DisplayClass0_1.<<Initialize>>b__125()
   at Submission#0.<<Initialize>>b__0_96(String tool, Action action)
   at Submission#0.<<Initialize>>b__0_35(ICakeContext context, BuildVersion buildVersion)
   at Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass24_0.<Does>b__0(ICakeContext x)
   at Cake.Core.CakeTask.<Execute>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.DefaultExecutionStrategy.<ExecuteAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.CakeEngine.<ExecuteTaskAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.CakeEngine.<RunTask>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Cake.Core.CakeEngine.<RunTargetAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Scripting.BuildScriptHost.<RunTargetAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.Scripting.ScriptHost.RunTarget(String target)
   at Submission#0.<get_Build>b__669_0(String target)
   at Submission#0.Builder.Run()
   at Submission#0.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.<RunSubmissionsAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Scripting.Script`1.<RunSubmissionsAsync>d__21.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Cake.Scripting.Roslyn.RoslynScriptSession.Execute(Script script)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
   at Cake.Commands.BuildCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(CakeOptions options)
   at Cake.Program.Main()
---> (Inner Exception #0) Cake.Core.CakeException: MSBuild: Process returned an error (exit code 1).
   at Cake.Core.Tooling.Tool`1.ProcessExitCode(Int32 exitCode)
   at Cake.Core.Tooling.Tool`1.Run(TSettings settings, ProcessArgumentBuilder arguments, ProcessSettings processSettings, Action`1 postAction)
   at Cake.Common.Tools.MSBuild.MSBuildAliases.MSBuild(ICakeContext context, FilePath solution, MSBuildSettings settings)
   at Submission#0.MSBuild(FilePath solution, MSBuildSettings settings)
   at Submission#0.<>c__DisplayClass0_1.<<Initialize>>b__125()
   at Submission#0.<<Initialize>>b__0_96(String tool, Action action)
   at Submission#0.<<Initialize>>b__0_35(ICakeContext context, BuildVersion buildVersion)
   at Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass24_0.<Does>b__0(ICakeContext x)
   at Cake.Core.CakeTask.<Execute>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.DefaultExecutionStrategy.<ExecuteAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.CakeEngine.<ExecuteTaskAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.CakeEngine.<RunTask>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Cake.Core.CakeEngine.<RunTargetAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Scripting.BuildScriptHost.<RunTargetAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.Scripting.ScriptHost.RunTarget(String target)
   at Submission#0.<get_Build>b__669_0(String target)
   at Submission#0.Builder.Run()
   at Submission#0.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.<RunSubmissionsAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Scripting.Script`1.<RunSubmissionsAsync>d__21.MoveNext()<---
```

**Comment by punker76** [comment]
@aminya LGTM 👍🏻 
/cc @gep13

**Comment by aminya** [comment]
I still get errors when I try to run this locally:
```ps1
========================================
Strong-Name-Signer
========================================
InputDirectoryString: Source\packages\Splat*
Error: Failed to resolve assembly: 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null'

.NET Assembly Strong-Name Signer Summary
5 file(s) were strong-name signed.
0 references(s) were fixed.

========================================
Build
========================================
Building Source/ChocolateyGui.sln
Microsoft (R) Build Engine version 16.7.0+b89cb5fde for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 2021-02-11 2:55:44 PM.
     1>Project "C:\Users\aminy\Documents\GitHub\C#\ChocolateyGUI\Source\ChocolateyGui.sln" on node 1 (Build target(s)).
     1>MSBUILD : warning MSB4010: The "*.tasks" files could not be successfully loaded from their expected location "C:
       \Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\amd64". Default tasks will not
       be available.  [C:\Users\aminy\Documents\GitHub\C#\ChocolateyGUI\Source\ChocolateyGui.sln]
     1>C:\Users\aminy\Documents\GitHub\C#\ChocolateyGUI\Source\ChocolateyGui.sln.metaproj : error MSB4036: The "Message
       " task was not found. Check the following: 1.) The name of the task in the project file is the same as the name
       of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface.
       3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the
       "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\amd64" directory. [C:\Users\
       aminy\Documents\GitHub\C#\ChocolateyGUI\Source\ChocolateyGui.sln]
     1>Done Building Project "C:\Users\aminy\Documents\GitHub\C#\ChocolateyGUI\Source\ChocolateyGui.sln" (Build target(
       s)) -- FAILED.

Build FAILED.

       "C:\Users\aminy\Documents\GitHub\C#\ChocolateyGUI\Source\ChocolateyGui.sln" (Build target) (1) ->
       (ValidateSolutionConfiguration target) ->
         MSBUILD : warning MSB4010: The "*.tasks" files could not be successfully loaded from their expected location "
       C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\amd64". Default tasks will no
       t be available.  [C:\Users\aminy\Documents\GitHub\C#\ChocolateyGUI\Source\ChocolateyGui.sln]


       "C:\Users\aminy\Documents\GitHub\C#\ChocolateyGUI\Source\ChocolateyGui.sln" (Build target) (1) ->
       (ValidateSolutionConfiguration target) ->
         C:\Users\aminy\Documents\GitHub\C#\ChocolateyGUI\Source\ChocolateyGui.sln.metaproj : error MSB4036: The "Messa
       ge" task was not found. Check the following: 1.) The name of the task in the project file is the same as the nam
       e of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface
       . 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in th
       e "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\amd64" directory. [C:\User
       s\aminy\Documents\GitHub\C#\ChocolateyGUI\Source\ChocolateyGui.sln]

    1 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.24
An error occurred when executing task 'Build'.

----------------------------------------
Teardown
----------------------------------------
Starting Teardown...
Finished running tasks.
Error: One or more errors occurred.
        MSBuild: Process returned an error (exit code 1).

```

**Comment by punker76** [comment]
@aminya I don't know what this means "MSBUILD : warning MSB4010: The "*.tasks" files could not be successfully loaded from their expected location" maybe a corrupt VS installation?

**Comment by aminya** [comment]
I updated my Visual Studio to the latest preview, but still I get errors. 

<details>
<summary>Details</summary>


```ps1
========================================
Build
========================================
Executing task: Build
Executing: "C:/Users/aminy/Documents/GitHub/C#/ChocolateyGUI/tools/Cake/Cake.exe" "C:/Users/aminy/Documents/GitHub/C#/ChocolateyGUI/bc0aeab7-f6da-4d44-af92-69033efed850.cake" -nuget_useinprocessclient="true" -settings_skipverification="true"
Deleting file C:/Users/aminy/Documents/GitHub/C#/ChocolateyGUI/bc0aeab7-f6da-4d44-af92-69033efed850.cake
Building Source/ChocolateyGui.sln
Executing: "C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/MSBuild/Current/Bin/amd64/MSBuild.exe" /m /v:normal /p:Configuration="Release" /p:Platform="Any CPU" /p:TreatWarningsAsErrors=True /target:Build /logger:XmlFileLogger,"C:/Users/aminy/Documents/GitHub/C#/ChocolateyGUI/tools/MSBuild.Extension.Pack.1.9.1/tools/net40/MSBuild.ExtensionPack.Loggers.dll";logfile="BuildArtifacts/MsBuild.log";invalidCharReplacement=_;verbosity=Detailed;encoding=UTF-8 "C:/Users/aminy/Documents/GitHub/C#/ChocolateyGUI/Source/ChocolateyGui.sln"
Microsoft (R) Build Engine version 16.7.0+b89cb5fde for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 2021-02-11 11:57:27 PM.
     1>Project "C:\Users\aminy\Documents\GitHub\C#\ChocolateyGUI\Source\ChocolateyGui.sln" on node 1 (Build target(s)).
     1>MSBUILD : warning MSB4010: The "*.tasks" files could not be successfully loaded from their expected location "C:
       \Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\amd64". Default tasks will not
       be available.  [C:\Users\aminy\Documents\GitHub\C#\ChocolateyGUI\Source\ChocolateyGui.sln]
     1>C:\Users\aminy\Documents\GitHub\C#\ChocolateyGUI\Source\ChocolateyGui.sln.metaproj : error MSB4036: The "Message
       " task was not found. Check the following: 1.) The name of the task in the project file is the same as the name
       of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface.
       3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the
       "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\amd64" directory. [C:\Users\
       aminy\Documents\GitHub\C#\ChocolateyGUI\Source\ChocolateyGui.sln]
     1>Done Building Project "C:\Users\aminy\Documents\GitHub\C#\ChocolateyGUI\Source\ChocolateyGui.sln" (Build target(
       s)) -- FAILED.

Build FAILED.

       "C:\Users\aminy\Documents\GitHub\C#\ChocolateyGUI\Source\ChocolateyGui.sln" (Build target) (1) ->
       (ValidateSolutionConfiguration target) ->
         MSBUILD : warning MSB4010: The "*.tasks" files could not be successfully loaded from their expected location "
       C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\amd64". Default tasks will no
       t be available.  [C:\Users\aminy\Documents\GitHub\C#\ChocolateyGUI\Source\ChocolateyGui.sln]


       "C:\Users\aminy\Documents\GitHub\C#\ChocolateyGUI\Source\ChocolateyGui.sln" (Build target) (1) ->
       (ValidateSolutionConfiguration target) ->
         C:\Users\aminy\Documents\GitHub\C#\ChocolateyGUI\Source\ChocolateyGui.sln.metaproj : error MSB4036: The "Messa
       ge" task was not found. Check the following: 1.) The name of the task in the project file is the same as the nam
       e of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface
       . 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in th
       e "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\amd64" directory. [C:\User
       s\aminy\Documents\GitHub\C#\ChocolateyGUI\Source\ChocolateyGui.sln]

    1 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.13
An error occurred when executing task 'Build'.

----------------------------------------
Teardown
----------------------------------------
Executing custom teardown action...
Starting Teardown...
Finished running tasks.
Error: System.AggregateException: One or more errors occurred. ---> Cake.Core.CakeException: MSBuild: Process returned an error (exit code 1).
   at Cake.Core.Tooling.Tool`1.ProcessExitCode(Int32 exitCode)
   at Cake.Core.Tooling.Tool`1.Run(TSettings settings, ProcessArgumentBuilder arguments, ProcessSettings processSettings, Action`1 postAction)
   at Cake.Common.Tools.MSBuild.MSBuildAliases.MSBuild(ICakeContext context, FilePath solution, MSBuildSettings settings)
   at Submission#0.MSBuild(FilePath solution, MSBuildSettings settings)
   at Submission#0.<>c__DisplayClass0_1.<<Initialize>>b__125()
   at Submission#0.<<Initialize>>b__0_96(String tool, Action action)
   at Submission#0.<<Initialize>>b__0_35(ICakeContext context, BuildVersion buildVersion)
   at Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass24_0.<Does>b__0(ICakeContext x)
   at Cake.Core.CakeTask.<Execute>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.DefaultExecutionStrategy.<ExecuteAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.CakeEngine.<ExecuteTaskAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.CakeEngine.<RunTask>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Cake.Core.CakeEngine.<RunTargetAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Scripting.BuildScriptHost.<RunTargetAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.Scripting.ScriptHost.RunTarget(String target)
   at Submission#0.<get_Build>b__669_0(String target)
   at Submission#0.Builder.Run()
   at Submission#0.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.<RunSubmissionsAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Scripting.Script`1.<RunSubmissionsAsync>d__21.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Cake.Scripting.Roslyn.RoslynScriptSession.Execute(Script script)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
   at Cake.Commands.BuildCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(CakeOptions options)
   at Cake.Program.Main()
---> (Inner Exception #0) Cake.Core.CakeException: MSBuild: Process returned an error (exit code 1).
   at Cake.Core.Tooling.Tool`1.ProcessExitCode(Int32 exitCode)
   at Cake.Core.Tooling.Tool`1.Run(TSettings settings, ProcessArgumentBuilder arguments, ProcessSettings processSettings, Action`1 postAction)
   at Cake.Common.Tools.MSBuild.MSBuildAliases.MSBuild(ICakeContext context, FilePath solution, MSBuildSettings settings)
   at Submission#0.MSBuild(FilePath solution, MSBuildSettings settings)
   at Submission#0.<>c__DisplayClass0_1.<<Initialize>>b__125()
   at Submission#0.<<Initialize>>b__0_96(String tool, Action action)
   at Submission#0.<<Initialize>>b__0_35(ICakeContext context, BuildVersion buildVersion)
   at Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass24_0.<Does>b__0(ICakeContext x)
   at Cake.Core.CakeTask.<Execute>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.DefaultExecutionStrategy.<ExecuteAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.CakeEngine.<ExecuteTaskAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.CakeEngine.<RunTask>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Cake.Core.CakeEngine.<RunTargetAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Scripting.BuildScriptHost.<RunTargetAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.Scripting.ScriptHost.RunTarget(String target)
   at Submission#0.<get_Build>b__669_0(String target)
   at Submission#0.Builder.Run()
   at Submission#0.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.<RunSubmissionsAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Scripting.Script`1.<RunSubmissionsAsync>d__21.MoveNext()<---

``` 

</details>

**Comment by gep13** [comment]
>@aminya said...
I updated my Visual Studio to the latest preview, but still, I get errors. I think I should just give up building it, and I wish that you can fix

It is great that you want to work on this issue, however, there should be no requirement for this PR in order to make that happen.

I currently have the Chocolatey GUI solution open in Visual Studio 2019, without any of the changes in this PR:

image

**Comment by aminya** [comment]
I just wanted to avoid installing some ancient version of Visual Studio to be able to build the project. 

Anyway, this PR should be reviewed independently of that issue.

**Comment by gep13** [comment]
I just want to confirm that you have seen the instructions here:

https://github.com/chocolatey/ChocolateyGUI#building

Did neither of the suggested workarounds work for you?

**Comment by gep13** [comment]
Actually, based on the contents of this PR, it looks like you did see this, so you must be aware that it isn't necessary to install an older version of Visual Studio to get the build to work.

**Comment by gep13** [comment]
@aminya I have just tested this PR on a machine that only have Visual Studio 2019 installed, and I can confirm that it works as expected, in the same way that it does on the AppVeyor CI build.

As such, I am going to move forward on getting this merged in.

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@aminya your changes have been merged, thanks for your contribution 👍

**Pull request merged**
