### PR TITLE
(GH-620) Fix showing selected source after editing source.

### PR DESCRIPTION
**Pull request by DamianMaslanka5**
* Changed `SelectedItem` to `CurrentItem`
 `SelectedItem` is not getting updated after change to any source, I'm not sure why.
* Added `DraftSource` to prevent updating `SelectedSource` if save button was not clicked.
* Disabled multi select.

### CODE REVIEW

**Comment by gep13** [comment]
Relates to #620

**Comment by gep13** [comment]
@DamianMaslanka5 apologies for not getting to this sooner, I am only just seeing it now.

I have just taken this for a spin, and on the whole, it looks good, however, I am seeing one issue with this change.  If I do the following:

* select a source, make a change, and then save it
* click a different source
* click back onto the source that was changed
* click on the same different source

Then I get the following exception:

image

I haven't had a chance to dig into this yet, but I thought I would respond here in case you knew immediately what the problem is.

**Comment by DamianMaslanka5** [comment]
@gep13 No problem. I fixed the issue and i found source of the bug. DataGrid is using GetHashCode and Equals but in ChocolateySource these methods are overriden and you probably know that if property is mutable it shouldn't be used in GetHashCode. If we don't modify the source directly it works well. If it looks good for you let me know and I will squash the commits, or you can do it.

**Comment by gep13** [comment]
@DamianMaslanka5 I have just taken this for a spin, and it is now working perfectly.

Thank you again for taking the time to do this!

**Pull request merged**
