### PR TITLE
(GH-742) Add empty item template to local source

### PR DESCRIPTION
**Pull request by gep13**

### CODE REVIEW

**Comment by gep13** [comment]
@punker76 can you please tell me why the empty item template isn't working on the local source?

I have tried to copy/paste your code, but there must be a bit more to it, and hoping that you can help :-)

**Comment by punker76** [comment]
@gep13 The empty results info should now work for tile and datagrid view.

choco_search_result_local

**Comment by punker76** [comment]
@gep13 I improved a little bit more here. The trigger for the empty template looks now also to the IsLoaded property to prevent showing it if the user refresh packages. The other one is the 250ms delay on search text box, so that the search is done after this and not directly on every user input.

**Comment by punker76** [comment]
choco_search_result_local2

**Comment by gep13** [comment]
@punker76 quick question... Does this:

> The other one is the 250ms delay on search text box, so that the search is done after this and not directly on every user input.

Take into account the UseDelayedSearch feature?

image

**Comment by punker76** [comment]
@gep13 The UseDelayedSearch is currently only for the remote service, because of long running task. IMO the local view doesn’t need that, because the search goes directly to the CollectionView and is faster.

**Comment by gep13** [comment]
@punker76 that is a great point!  I think we need to update the description to reflect that this only applies to the remote sources, but I can do that separately.

**Pull request merged**
