### PR TITLE
(GH-431) Added different background for outdated packages.

### PR DESCRIPTION
**Pull request by DamianMaslanka5**
Related to #431

Any suggestions for the color?
If package is selected or mouse is over the colors should be different or the same as for up to date packages?

outdatedpackagebackground

### CODE REVIEW

**Comment by gep13** [comment]
@DamianMaslanka5 nice, great work on this!

I am about as far from a designer as you can get, so not sure if I will be able to made a sensible suggestion here 😄 

@punker76 @pascalberger @RichiCoder1 @ferventcoder @mwallner what are your collective thoughts on this?  What should the colour of the background of the row be when the package is outdated?

**Comment by ferventcoder** [comment]
I like that their is some visual indication here. I know with the tiles aspect there is already a banner which is very helpful as well!

**Comment by mwallner** [comment]
To me, this looks AMAZING! 👍

**Comment by DamianMaslanka5** [comment]
outdatedpackagebackground

**Comment by gep13** [comment]
@DamianMaslanka5 of the two options, I prefer the second one 😄

**Comment by pascalberger** [comment]
@DamianMaslanka5 Nice addition 👍  I also prefer the second one

**Comment by ferventcoder** [comment]
Numero dos for me!

**Comment by punker76** [comment]
I'm putting a new proposal in the round... ;-)

It's the same overlay like in the tile view in a horizontal way.

2018-02-21_22h11_49

/cc @gep13 @ferventcoder @mwallner @pascalberger @RichiCoder1

**Comment by gep13** [comment]
@punker76 if I am honest, I think I prefer this version, as it is more in keeping with the Tile View that we have.

@DamianMaslanka5 what are your thoughts?

**Comment by DamianMaslanka5** [comment]
@gep13 I think it fits in better

**Comment by mwallner** [comment]
hey @DamianMaslanka5 great work! - please fix the codacy and dupfinder issues and I'll be happy to merge this PR :-)

**Comment by gep13** [comment]
@DamianMaslanka5 thanks again for another fix!  I have merged this into develop here: https://github.com/chocolatey/ChocolateyGUI/commit/ad63a458affefb7f316d8d7acd538a80a1d7305a

**Pull request closed without merging**
