### PR TITLE
New Cake Build for ChocolateyGUI

### PR DESCRIPTION
**Pull request by gep13**
- Makes use of Cake.Recipe (https://github.com/cake-contrib/Cake.Recipe)
- This is likely going to fail on AppVeyor, as I have removed the WiX Binaries that were in the tools folder
- This portion will need to be refactored

@RichiCoder1 @pascalberger  Happy to accept any comments that you have on this.

### CODE REVIEW

**Comment by gep13** [comment]
Interesting... AppVeyor already has WiX installed (https://www.appveyor.com/docs/installed-software/) so the build is working.

I don't like relying on that though, and I will switch to using the WiX NuGet package at some point, but for now, I think I will keep working on the other parts.

There are some dupfinder issues in the code base just now, that it the reason for the build failure.

**Comment by RichiCoder1** [comment]
Weirdly enough, I'm ok having Wix as a preinstalled dependency for now (as long as we document it).

**Comment by gep13** [comment]
>@RichiCoder1 said...
Weirdly enough, I'm ok having Wix as a preinstalled dependency for now (as long as we document it).

The experience for new people coming onto the project could be a little jarring, when they try to build, and it doesn't work, so yes, we will need to document it.  Something I will need to get fixed though.  Not the highest priority just now though.

**Comment by RichiCoder1** [comment]
Yah, that dupfinder is going to be super unhappy for now. Lots of duplicate code.

**Comment by gep13** [comment]
>@RichiCoder1 said...
Yah, that dupfinder is going to be super unhappy for now. Lots of duplicate code.

Ha ha, yeah, noticed that.  If there are other files that you want to exclude from the dupfinder check, we can add them into the SetToolSettings call.

**Comment by gep13** [comment]
>@RichiCoder1 said...
That's seriously impressive how compact that setup.cake is.

Thanks!  It has taken a while to get Cake.Recipe to where it is just now, but it is starting to take shape, and the more projects it is used on, the more flexible it can become.  Having to add in some features just now, to accommodate what ChocolateyGUI requires, but it is all for the greater good :smile:

**Comment by RichiCoder1** [comment]
>> @RichiCoder1 said...
>> Yah, that dupfinder is going to be super unhappy for now. Lots of duplicate code.

> Ha ha, yeah, noticed that. If there are other files that you want to exclude from the dupfinder check, we can add them into the SetToolSettings call.
>> @RichiCoder1 said...
>> Yah, that dupfinder is going to be super unhappy for now. Lots of duplicate code.

> Ha ha, yeah, noticed that. If there are other files that you want to exclude from the dupfinder check, we can add them into the SetToolSettings call.

I'm going to say probably Hacks.cs and one other, but I'd need to the report. Speaking of which....

**Comment by gep13** [comment]
>@RichiCoder1 said...
Reports and other build artifacts don't appear to be getting picked up in appveyor.

Yip, I haven't added any of the Environment Variables for the Project in AppVeyor yet.  Cake.Recipe is really controlled by the top level settings in setup.cake and the presence of certain Environment Variables.  If they aren't there, then the build silently skips those steps.

**Comment by gep13** [comment]
@RichiCoder1 currently working on adding the download of the ReleaseNotes into the build process, and then was going to circle back around to that.

**Comment by gep13** [comment]
@RichiCoder1 ok, this is now successfully creating the Chocolatey Package, as you can see here:

https://ci.appveyor.com/project/chocolatey/chocolateygui/build/0.14.0-PullRequest.369+175.build.125#L771

All that is left to getting a successful build is fixing the dupfinder issues :smile:

**Comment by gep13** [comment]
>@RichiCoder1 said...
Reports and other build artifacts don't appear to be getting picked up in appveyor.

That normally happens at the end of the build, i.e. when it is successful, but sounds like you have another expectation, or, I am simply not understanding.  With the build in it's current "broken" state, what artifacts would you expect to see?

**Comment by gep13** [comment]
@RichiCoder1 I guess the DupFinder report would be very useful in this scenario.  Ok, let me take care of that, this will be a change in Cake.Recipe.

**Comment by RichiCoder1** [comment]
@gep13 Yup, test results & dup finder/other analysis reports. If it fails the build, I want to be able to quickly and easily diagnose why :)

**Comment by gep13** [comment]
@RichiCoder1 ok, now we are getting somewhere 😄 

Have a look here:

https://ci.appveyor.com/project/chocolatey/chocolateygui/build/0.14.0-PullRequest.369+175.build.126/artifacts

And you will find that a `dupfinder.html` is not an artifact of the build.  If you download this, you will see something similar to this:

image

If you have the TeamCity Extension for Visual Studio installed, within the ChocolateyGUI solution open, clicking on those links should take you directly to the affected lines.

**Comment by RichiCoder1** [comment]
Whoop, nice!

**Comment by RichiCoder1** [comment]
I'll see about getting those Dups "fixed" so we can get a green build.

**Comment by gep13** [comment]
>@RichiCoder1 said...
I'll see about getting those Dups "fixed" so we can get a green build.

I have taken a stab at it.  Just away to push.  You can let me know what you think of the changes.

**Comment by gep13** [comment]
@RichiCoder1 and we have a green build! 🎉

**Comment by RichiCoder1** [comment]
@gep13 Nice! I'm all good to merge whenever you're comfortable :)

**Comment by gep13** [comment]
Assuming you are ok with the dupfinder changes, then I think this is good to go.

**Comment by RichiCoder1** [comment]
👍 :shipit:

**Comment by RichiCoder1** [comment]
@gep13 What's status here?

**Comment by gep13** [comment]
Only thing that is missing is the style cop addition.

**Comment by gep13** [comment]
@RichiCoder1 so, having some "issues" getting the StyleCop.Analyzers to work.  They seem to work for one, or the other project (i.e. ChocolateyGui and ChocolateyGui.SubProcess) but not for both projects at the same time.  Not sure what is going on.  Will try to dig into it some more over the weekend.

**Comment by gep13** [comment]
@RichiCoder1 ok, StyleCop has now been added to the build.  Let me know your thoughts on the rules that I have left in place.

**Comment by gep13** [comment]
@RichiCoder1 okay, this is ready to go.

I have set up the MyGet feed to use again use `https://www.myget.org/F/chocolateygui/api/v2` rather than my personal one.

**Comment by RichiCoder1** [comment]
LGTM! I'm sure I'll probably end up tweaking it, but nothing objectable so far.

**Comment by gep13** [comment]
@RichiCoder1 sweet!

**Comment by RichiCoder1** [comment]
Are we good to merge, or is there anything else you'd like to tackle first?

**Comment by gep13** [comment]
I think we are good. I have raised another issue for the Wyam Docs.

**Comment by RichiCoder1** [comment]
Whoop! I'm going to be working tomorrow(today) on a lot of backlog that still present. Hopefully should have something close to delivery soon :)

**Pull request merged**
