### PR TITLE
(GH-685) Update MahApps to latest source and introduce a dark mode

### LINKED ISSUE #685: Add a dark mode
This could be put into the settings panel.

### PR DESCRIPTION
**Pull request by punker76**
Changes

- [x] Update MahApps to latest source
- [x] Update MahApps IconPacks to latest one
- [x] Use more Win 10 styles where it is possible to improve UI/UX
- [x] Improve some Styles inherited from MahApps to work perfectly together with a dark mode
- [x] Introduce a dark mode
- [x] Allow changing dark/light theme
- [x] BundledTheme as a Service
- [x] Dark/Light ToggleSwitch like on the web size (not exactly but similar)
- [x] Save the Dark/Light theme selection?

**Preview**

image

image

image

image

image

Closes #685

### CODE REVIEW

**Comment by opusforlife2** [comment]
This looks amazing. :') Thanks a lot for working on this.

**Comment by TheNavyBear** [comment]
Thank you so much for working on this, it is greatly appreciated!

**Review by Patreos98 — APPROVED** [review]

**Comment by punker76** [comment]
current status

chocolateygui_dark_mode

**Comment by lucknaumann** [comment]
@punker Thanks for working on this! It's looking great! Excited for this to be finalized, merged, and released into the wild! 😉

**Comment by punker76** [comment]
next update

2021-02-17_23h39_05

2021-02-17_23h39_23

2021-02-17_23h39_32

2021-02-17_23h39_38

**Comment by punker76** [comment]
It's  almost done... only some minor tweaks...

2021-02-19_15h47_42

2021-02-19_15h48_58

2021-02-19_15h49_07

2021-02-19_15h49_17

**Comment by opusforlife2** [comment]
Looks brilliant! My eyes are thanking you already.

**Comment by punker76** [comment]
chocolateygui_dark_mode_5

**Comment by gep13** [comment]
@punker76 just taken this for a spin, and so far, it all looks good to me!  Thank you again for doing all this work, it is truly appreciated!

Do you think it would make sense to condense the commits into a smaller number of commits, or did you want to merge as is?  If nothing else, could the commit messages be updated to include the issue number in the message, i.e:

```
(#685) Add ThemeMode and own ToggleSwitch with icons
```

instead of:

```
Add ThemeMode and own ToggleSwitch with icons
```

I notice that there is one item left on the list:

> Save the Dark/Light theme selection?

Did you have a plan for how this should be handled?  Ideally, this would be persisted in the same way as the other Chocolatey GUI features are enabled/disabled, so that this setting can be enabled once at installation item.

What is the correct way to know whether the application is currently using the Light or the Dark theme?  I am thinking about what I need to do in the Chocolatey GUI Licensed Extension to provide the ability for light/dark images, and to know which ones to show based on what theme is currently selected.

**Comment by punker76** [comment]
> @punker76 just taken this for a spin, and so far, it all looks good to me! Thank you again for doing all this work, it is truly appreciated!

❤️ 

> Do you think it would make sense to condense the commits into a smaller number of commits, or did you want to merge as is? If nothing else, could the commit messages be updated to include the issue number in the message, i.e:
> 
> ```
> (#685) Add ThemeMode and own ToggleSwitch with icons
> ```
> 
> instead of:
> 
> ```
> Add ThemeMode and own ToggleSwitch with icons
> ```

I have squashed some commits and updated the MahApps lib to the latest and the commit messages now also contains the issue.

> 
> I notice that there is one item left on the list:
> 
> > Save the Dark/Light theme selection?
> 
> Did you have a plan for how this should be handled? Ideally, this would be persisted in the same way as the other Chocolatey GUI features are enabled/disabled, so that this setting can be enabled once at installation item.


> What is the correct way to know whether the application is currently using the Light or the Dark theme? I am thinking about what I need to do in the Chocolatey GUI Licensed Extension to provide the ability for light/dark images, and to know which ones to show based on what theme is currently selected.

To check which theme is currently used you can use the `BundledTheme` property at the `ThemeAssist`. It can be used in code behind and also in Xaml:

```
            <DataTrigger Binding="{Binding Source={x:Static theming:ThemeAssist.BundledTheme}, Path=IsLightTheme}" Value="True">
                <Setter Property="Background" ... />
            </DataTrigger>
```

The `IBundledThemeService` interface gives you 2 properties to check whats selected:

```
        /// <summary>
        /// Gets or sets a value indicating whether the current selected theme.
        /// </summary>
        ThemeMode ThemeMode { get; }

        /// <summary>
        /// Gets or sets a value indicating whether the current selected theme is the light theme.
        /// </summary>
        bool IsLightTheme { get; set; }
```

The `IsLightTheme` property can be used to change this at runtime.

The `ThemeMode` is the property which should be persist. The saved one must be passed as the parameter here (at the OnStartup in App.xaml.cs):

```
ThemeAssist.BundledTheme.SyncTheme(ThemeMode.WindowsDefault); // todo Use the saved mode
```

Maybe you can do the persistant part, but if not, let me know, then I will look for it.

**Comment by AdmiringWorm** [comment]
Overall looks pretty great, just one thing I'd like to note though.
The mix of white and the darkened font color before selecting any packages when a source is selected in the sidebar looks a bit off to me, and may cause problems with the eyesight of some users (just an assumption).

image

Same when a package is hovered over, which makes it a bit hard to read:
image

**Comment by punker76** [comment]
@AdmiringWorm Thx for the hint. ❤️  The problem here was maybe that I use always the tile view :-D Totally forgot to see how the old view looks in the dark mode. Will change this maybe this evening.

**Comment by punker76** [comment]
@gep13 @AdmiringWorm 

Here my changes to the standard view

2021-03-03_12h34_46

2021-03-03_12h35_38

2021-03-03_12h36_16

2021-03-03_12h36_40

And we can also show the icon...

2021-03-03_12h43_27

**Comment by punker76** [comment]
chocolateygui_dark_mode_7

**Comment by gep13** [comment]
@punker76 this looks amazing!

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@punker76 HUGE, HUGE, thank you for getting this work done, it truly looks amazing!

**Comment by lucknaumann** [comment]
@punker76 Wow! I am **SO** excited about this my eyes are bursting with joy!

**Pull request merged**
