### PR TITLE
(GH-170) Globalisation/Localisation

### PR DESCRIPTION
**Pull request by mwallner**
moving all neccessary strings to resx.
(translation from English to other languages in follow-up issues)

### CODE REVIEW

**Comment by mwallner** [comment]
the automatic language selection / some kind of dropdown for language selection (maybe in settings?) is still missing - open for any Ideas how / where to implement.

**Comment by gep13** [comment]
Should we default to the current user Locale, with an option to change?

**Comment by mwallner** [comment]
I'd say that's the preferred way, yes

**Comment by mwallner** [comment]
German localization on the way: https://github.com/mwallner/ChocolateyGUI/tree/feature/localization_de - where should we set the 'CultureInfo' ?

**Comment by RichiCoder1** [comment]
CultureInfo should get pulled automagically from the user's machine. It shouldn't, in theory, need to be set. There are ways to override an applications culture on startup if we want to add a manual override though.

**Comment by RichiCoder1** [comment]
For more deets: https://msdn.microsoft.com/en-us/library/system.globalization.cultureinfo.currentuiculture%28v=vs.110%29.aspx

**Comment by RichiCoder1** [comment]
I'll make sure I add strings for all future work, as well as go through and make sure all error messages have Resx sources.

**Pull request merged**
