### PR TITLE
GH480: Persist current package details

### PR DESCRIPTION
**Pull request by gep13**
@RichiCoder1 okay, so this feels sort of clunky, but...

Thoughts?

### CODE REVIEW

**Comment by gep13** [comment]
Could add some ignores to the Mapping Profile to ignore these values, but not sure if that is a wise move.

**Comment by RichiCoder1** [comment]
Hrmm. Would be nice to figure out a way to pull those values at the same time. But getting package details is already pretty expensive....

**Comment by gep13** [comment]
@RichiCoder1 I don't disagree.  Perhaps merge this and create a new issue to track improving this in a future release?

**Comment by RichiCoder1** [comment]
The property I added in #482 will probably also need to be persisted.

**Comment by gep13** [comment]
See related issue here: https://github.com/chocolatey/ChocolateyGUI/issues/485

**Pull request merged**
